/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Tree */

#ifndef _Included_Tree
#define _Included_Tree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Tree
 * Method:    createTree
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Tree_createTree
  (JNIEnv *, jobject);

/*
 * Class:     Tree
 * Method:    deleteTree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Tree_deleteTree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Tree
 * Method:    insert
 * Signature: (JIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_Tree_insert
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     Tree
 * Method:    find
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_Tree_find
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Tree
 * Method:    remove
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_Tree_remove
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     Tree
 * Method:    size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_Tree_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Tree
 * Method:    isEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_Tree_isEmpty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Tree
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Tree_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Tree
 * Method:    toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Tree_toString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
